version: '3'

services:
  postgres:
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=hacktiv-db
    ports:
      - 5432:5432
    networks:
      - hacktiv-backend

networks:
  hacktiv-backend:
